image: gitpod/workspace-full

tasks:
  - name: Docker Login & Build
    init: |
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      docker pull postgres:15-alpine
      docker-compose build
    command: |
      echo "Waiting for Voting App at $(gp url 5000)..."
      gp ports await 5000
      echo "Voting: $(gp url 5000)"
      echo "Results: $(gp url 5001)"

  - name: Run App
    command: docker-compose -f docker-compose.yml up
    openMode: split-right

ports:
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: open-preview
  - port: 5858
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
